### ISSUE TITLE
av_err2str build failure regression on Linux

### ISSUE THREAD

**Issue by neptuwunium** [shadps4-emu/shadPS4#1457]
https://github.com/shadps4-emu/shadPS4/blob/9d6eee6acfaeac7b33c8e99fb336a243d64c060b/src/core/libraries/videodec/videodec2_impl.cpp#L221 uses the unmodified av_err2str which causes build failures

previously fixed in https://github.com/shadps4-emu/shadPS4/pull/815, the modified macro exists in https://github.com/shadps4-emu/shadPS4/blob/9d6eee6acfaeac7b33c8e99fb336a243d64c060b/src/core/libraries/avplayer/avplayer_source.cpp#L25-L34

copying over that macro to videodec2_impl.cpp fixes the builds.
likely should move the macro to a common source point to prevent this regression in the future.

**Comment by polybiusproxy** [comment]
Fixed with 2918335

**Comment by neptuwunium** [comment]
Thanks!

**Comment by OPNA2608** [comment]
Regressed again:

```
In file included from /build/source/src/common/assert.h:7,
                 from /build/source/src/core/libraries/ajm/ajm_mp3.cpp:4:
/build/source/src/core/libraries/ajm/ajm_mp3.cpp: In member function 'AVFrame* Libraries::Ajm::AjmMp3Decoder::ConvertAudioFrame(AVFrame*)':
/build/source/src/core/libraries/ajm/ajm_mp3.cpp:97:64: error: taking address of temporary array
   97 |         LOG_ERROR(Lib_AvPlayer, "Could not convert frame: {}", av_err2str(res));
      |                                                                ^~~~~~~~~~
/build/source/src/common/logging/log.h:66:32: note: in definition of macro 'LOG_ERROR'
   66 |                                __VA_ARGS__)
      |                                ^~~~~~~~~~~
make[2]: *** [CMakeFiles/shadps4.dir/build.make:1214: CMakeFiles/shadps4.dir/src/core/libraries/ajm/ajm_mp3.cpp.o] Error 1
```

Introduced in https://github.com/shadps4-emu/shadPS4/pull/1456:

https://github.com/shadps4-emu/shadPS4/blob/941a668f78845290b4f5b28f2246c6cf00de765e/src/core/libraries/ajm/ajm_mp3.cpp#L95-L97
