### PR TITLE
Add HDR option to settings menu

### PR DESCRIPTION
**Pull request by tomboylover93**
Adds an option to the settings dialog window for the HDR option introduced in #2381. Also adds `setAllowHDR` to the config.h and config.cpp files, so that there are no compilation errors.

image

### CODE REVIEW

**Comment by ghost** [comment]
i know it is already merged but why not add it to graphics?

**Comment by tomboylover93** [comment]
I was considering that but since it's defined under "General" instead of "GUI" in config.cpp I decided not to.
