### ISSUE TITLE
[APP BUG]: Weird build error in src/video_core/renderer_vulkan/vk_platform.cpp:402:28

### ISSUE THREAD

**Issue by v-fox** [shadps4-emu/shadPS4#2106]
### Checklist

- [X] I have searched for a similar issue in this repository and did not find one.
- [X] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

Tried to make a [package build](https://build.opensuse.org/package/show/home:X0F:branches:Emulators/shadPS4) of latest git snapshot (20250108.65f9bbbf) and got this:
```
[  314s] /home/abuild/rpmbuild/BUILD/shadPS4-20250108.65f9bbbf/src/video_core/renderer_vulkan/vk_platform.cpp:402:28: error: cannot initialize a member subobject of type 'vk::PFN_DebugUtilsMessengerCallbackEXT' (aka 'unsigned int (*)(vk::DebugUtilsMessageSeverityFlagBitsEXT, Flags<DebugUtilsMessageTypeFlagBitsEXT>, const vk::DebugUtilsMessengerCallbackDataEXT *, void *)') with an lvalue of type 'VkBool32 (VkDebugUtilsMessageSeverityFlagBitsEXT, VkDebugUtilsMessageTypeFlagsEXT, const VkDebugUtilsMessengerCallbackDataEXT *, void *)' (aka 'unsigned int (VkDebugUtilsMessageSeverityFlagBitsEXT, unsigned int, const VkDebugUtilsMessengerCallbackDataEXT *, void *)'): type mismatch at 1st parameter ('vk::DebugUtilsMessageSeverityFlagBitsEXT' vs 'VkDebugUtilsMessageSeverityFlagBitsEXT')
[  314s]   402 |         .pfnUserCallback = DebugUtilsCallback,
[  314s]       |                            ^~~~~~~~~~~~~~~~~~
[  314s] 1 error generated.
```

System is a rolling release with latest userspace, including vulkan-headers and vulkan-validationlayers of 1.4.304
According to commit history, this seems to relate to pretty old code introduced in https://github.com/shadps4-emu/shadPS4/commit/c01b6f839781be08a2e675c172cac6d172a4d1d1 
Have no clue what it actually complains about.

### Reproduction Steps

Seems like making a normal build against fresh userspace would cause it, not sure why it's not broken for everyone.

### Expected Behavior

Complete the build.

### Specify OS Version

openSUSE Tumbleweed

**Comment by Hermiten** [comment]
Maybe because you use a specific Linux system, with different package not the good version. Idk, can you check if you have everything up to date ?

**Comment by v-fox** [comment]
> Maybe because you use a specific Linux system, with different package not the good version. Idk, can you check if you have everything up to date ?

Tumbleweed is a rolling release, so everything should have latest stable release (sometimes unstable) unless maintainer for some package have gone missing. If you look at the link above and click on "[x86_64 -> [failed]](https://build.opensuse.org/package/live_build_log/home:X0F:branches:Emulators/shadPS4/openSUSE_Tumbleweed/x86_64)", it will show [the build log](https://build.opensuse.org/build/home:X0F:branches:Emulators/openSUSE_Tumbleweed/x86_64/shadPS4/_log), starting with list of all packages used with their versions.

**Comment by v-fox** [comment]
As I've suspected, it was related to vulkan-headers and caused by my version being "too new", not too old: https://github.com/shadps4-emu/shadPS4/pull/2190
