### ISSUE TITLE
[APP BUG]: time.cpp:534:5: error: a type specifier is required for all declarations

### ISSUE THREAD

**Issue by Martinfx** [shadps4-emu/shadPS4#3649]
### Checklist

- [x] I have searched for a similar issue in this repository and did not find one.
- [x] I am using an official build obtained from [releases](https://github.com/shadps4-emu/shadPS4/releases) or updated one of those builds using its in-app updater.

### Describe the Bug

Hi,
i build with version 0.11.0 and clang19 on FreeBSD 14.3 and i have problem with time.cpp:534:5: error: a type specifier is required for all declarations

```
hadps4.dir/src/core/libraries/kernel/time.cpp.o -MF CMakeFiles/shadps4.dir/src/core/libraries/kernel/time.cpp.o.d -o CMakeFiles/shadps4.dir/src/core/libraries/kernel/time.cpp.o -c /home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:534:5: error: a type specifier is required for all declarations
  534 |     clock = std::make_unique<Common::NativeClock>();
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:535:5: error: a type specifier is required for all declarations
  535 |     initial_ptc = clock->GetUptime();
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:535:24: error: member reference base type 'clock_t ()' (aka 'int ()') is not a structure or union
  535 |     initial_ptc = clock->GetUptime();
      |                   ~~~~~^ ~~~~~~~~~
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:538:5: error: expected unqualified-id
  538 |     LIB_FUNCTION("yS8U2TGCe1A", "libkernel", 1, "libkernel", posix_nanosleep);
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/libs.h:11:5: note: expanded from macro 'LIB_FUNCTION'
   11 |     {                                                                                              \
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:539:5: error: expected unqualified-id
  539 |     LIB_FUNCTION("yS8U2TGCe1A", "libScePosix", 1, "libkernel", posix_nanosleep);
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/libs.h:11:5: note: expanded from macro 'LIB_FUNCTION'
   11 |     {                                                                                              \
      |     ^
/home/maxfx/Documents/FreeBSD-Ports/shadps4/work/shadPS4-v.0.11.0/src/core/libraries/kernel/time.cpp:540:5: error: expected unqualified-id
  540 |     LIB_FUNCTION("QcteRwbsnV0", "libkernel", 1, "libkernel", posix_usleep);
      |     ^

```

### Reproduction Steps

1. git clone 
2. cmake ..
3. make

### Specify OS Version

FreeBSD 14.3-RELEASE

### CPU

amd ryzen

### GPU

nvidia 1060

### Amount of RAM in GB

32

**Comment by red-prig** [comment]
As far as I know, FreeBSD is not supported by the project. You can send us a pull request with corrections.

**Comment by Martinfx** [comment]
> As far as I know, FreeBSD is not supported by the project. You can send us a pull request with corrections.

Yes but this is code shadps4 not specific code for freebsd

**Comment by red-prig** [comment]
If the problem is only reproduced on FreeBSD, I would say that FreeBSD's declarations are to blame.

**Comment by Martinfx** [comment]
> If the problem is only reproduced on FreeBSD, I would say that FreeBSD's declarations are to blame.

Did you test compile Shadps4 with Clang?

**Comment by squidbus** [comment]
> Did you test compile Shadps4 with Clang?

Our GitHub Actions CI compiles every commit on Windows, Linux, and macOS with clang, and Linux with gcc.

**Comment by Martinfx** [comment]
I fixed the problem with standart C++26 and llvm21
